language: python
os: linux
dist: xenial

python:
  - 3.6
  - 3.7
  - 3.8

compiler:
  - g++

jobs:
  include:
    - python: 3.8
      env:
        - COMPILER=clang
        - CC=clang
        - CXX=clang++
        - LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
      name: Linux clang (Python 3.8)

    - os: osx
      osx_image: xcode11  # python 3.7.4
      language: shell
      env:
        - TRAVIS_PYTHON_VERSION=3.7
        - PATH=/Users/travis/Library/Python/3.7/bin:$PATH
      name: OSX (Python 3.7)

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo -H apt-get -qq update; sudo -H apt-get install -y libfftw3-dev; fi
  # GalSim needs eigen...
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo -H apt-get install -y libeigen3-dev; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; brew install fftw; brew install eigen; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then export PIP=pip3; export PYTHON=python3; else export PIP=pip; export PYTHON=python; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install ccache; export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi

cache:
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Cellar
    - /usr/local/Homebrew
    - $HOME/.ccache

install:
  # Update pip executable. (Needs sudo on some systems.)
  - sudo -H $PIP install -U pip

  # Install dependencies
  - $PIP install -U numpy  # Do this first to clarify potential conflicts
  - $PIP install -U -r requirements.txt
  - $PIP install -U -r test_requirements.txt

script:
  - CMAKE_VERBOSE_MAKEFILE=1 $PYTHON setup.py install
  - cd tests; pytest --cov=batoid --cov-report=xml --cov-config .coveragerc; cd ../

after_success:
  - find ./build -iname "*.gcno" | grep /src/ | xargs -I{} gcov-4.8 {}
  - find ./build -iname "*.gcno" | grep /pysrc/ | xargs -I{} gcov-4.8 {}
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -rfv $HOME/.cache/pip/log
  - rm -rfv $HOME/.cache/pip/http
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew cleanup; fi
