branches:
  only:
    - master
language: cpp
sudo: false
matrix:
  include:
    - os: linux
      env: PYTHON=2.7 CPP=11 GCC=4.8
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test, kubuntu-backports]
          packages: [g++-4.8, cmake]
before_install:
  - |
    if [ -n "$CPP"]; then export CPP=-std=c++$CPP; fi
  - |
    pip install --user --upgrade pip virtualenv
    virtualenv -p python venv
    source venv/bin/activate
install:
  - |
    python setup.py install
script:
    pytest
