language: python

python:
  - 3.4
  - 3.5
  - 3.6

env:
  # These currently fail...
  # -
  #   - COMPILER=clang-3.3
  #   - CC=/usr/bin/clang
  #   - CXX=/usr/bin/clang++
  # -
  #   - COMPILER=clang-3.4
  #   - CC=/usr/bin/clang
  #   - CXX=/usr/bin/clang++
  -
    - COMPILER=clang
    - CC=clang
    - CXX=clang++
  -
    - COMPILER=gcc
    - CC=gcc
    - CXX=g++
  # Following don't seem to actually exist on travis-ci...
  # -
  #   - COMPILER=gcc-5.3
  #   - CC=gcc
  #   - CXX=g++
  # -
  #   - COMPILER=gcc-6.2
  #   - CC=gcc
  #   - CXX=g++

matrix:
  include:
    # Add a c++ code coverage build
    - python: 3.6
      env:
        - COMPILER=gcc
        - CC=gcc
        - CXX=g++
        - CMAKE_COVER=1
before_install:
  - |
    if [ "$COMPILER" == "clang-3.3" ];
    then
      sudo apt-get install clang-3.3 clang++-3.3
    fi
  - |
    if [ "$COMPILER" == "clang-3.4" ];
    then
      sudo apt-get install clang-3.4 clang++-3.4
    fi
  - |
    if [ "$COMPILER" == "gcc-5.3" ];
    then
      sudo apt-get install gcc-5.3
    fi
  - |
    if [ "$COMPILER" == "gcc-6.2" ];
    then
      sudo apt-get install gcc-6.2
    fi
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - export EIGEN_DIR=$PWD/eigen/
  - echo $EIGEN_DIR
  - sudo apt-get install -y libfftw3-dev
  - pip install -U setuptools pip==9.0
  - pip install numpy astropy future pyyaml LSSTDESC.Coord pybind11
  - pip install galsim

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/pip

install:
  - export CMAKE_VERBOSE_MAKEFILE=1
  - python setup.py develop

script:
  pytest --cov=batoid --cov-report=xml

after_success:
  - find ./build -iname "*.gcno" | grep /src/ | xargs -I{} gcov-4.8 {}
  - find ./build -iname "*.gcno" | grep /pysrc/ | xargs -I{} gcov-4.8 {}
  - bash <(curl -s https://codecov.io/bash)
