branches:
  only:
    - master
language: cpp
sudo: false
matrix:
  include:
    - os: linux
      env: PYTHON=2.7 CPP=11 GCC=4.8
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test, kubuntu-backports]
          packages: [g++-4.8, cmake]
    - os: linux
      env: PYTHON=3.5 CPP=11 GCC=4.8
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test, kubuntu-backports, deadsnakes]
          packages: [g++-4.8, cmake, python3.5-dev]
before_install:
  - export CPP=-std=c++$CPP
  - export CXX=g++-$GCC CC=gcc-$GCC
  - pip install --user --upgrade pip virtualenv
  - virtualenv -p python$PYTHON venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - pip install pytest
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/pip
install:
  python setup.py install
script:
  pytest tests/test_*.py
